version: '3'
services:
  order:
    build: ./fiap-order
    ports:
      - "8080:8080"
  order_db:
      image: postgres:latest
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        TZ: America/Sao_Paulo
        POSTGRES_PASSWORD: admin123
        POSTGRES_USER: postgres
        POSTGRES_DB: order
      ports:
        - 5432:5432